---
title: NCEI Passive Acoustics Archive
---

All ADRIFT, CCES, and PASCAL raw data and sound level metrics are publicly accessible through [NCEI Passive Acoustics Data Archive](https://www.ncei.noaa.gov/products/passive-acoustic-data). All data were packaged using a combination of automated scripts and the **NCEI Passive Packer tool**.

## Passive Packer Resources

[NCEI Passive Acoustic Data Viewer](https://www.ncei.noaa.gov/maps/passive-acoustic-data/)

[Passive Packer Manual](https://www.ngdc.noaa.gov/mgg/pad/packager_manual.pdf)

[Additional Archive Guidelines](https://drive.google.com/drive/folders/1ReEKFXMQ-SajJUyzTQFDVI9EnfKn9m8p?usp=sharing)

[ADRIFT Passive Packer Field Mapping](https://docs.google.com/spreadsheets/d/1G_QF8C8QnqvQg8lf0nBXWtaGW7ApnxId0c-qkmUYwcg/edit#gid=0)

## Hard Drive Requirements

### Guidelines

-   Only use Western Digital or Seagate Drives

    -   We bought 4 20TB [WD Elements Desktop Hard Drives](https://www.westerndigital.com/products/external-drives/wd-elements-desktop-usb-3-0-hdd#WDBWLG0200HBK-NESN) for PASCAL, CCES, and ADRIFT

-   Data can be packaged directly from its home directory to the destination external hard drive

-   All data and the metadata files created by Passive Packer must fit on the destination drive, ensure there is ample space on drive to reduce the risk of the program crashing

### External Hard Drive Name

Include the organization and project name without spaces in the hard drive name

-   Example: SWFSC_ADRIFT_DRIVE

### Physical Hard Drive Label

Physically label the drive with the following information easily visible

-   Packagers full name

-   Your organization

-   Project Name

-   Example: Kourtney Burger, SWFSC, ADRIFT 

## Getting Started

-   Download software from [Passive Packer Website](https://www.ncei.noaa.gov/products/passivepacker) and follow the 'Getting Started' directions

-   See [Passive Packer Manual](https://www.ngdc.noaa.gov/mgg/pad/packager_manual.pdf) for introduction to software and guidelines on packaging other passive acoustics data, including sound level metrics and moored deployments

-   You can manually fill in all Passive Packer fields following the guidelines and field descriptions in the [Passive Packer manual](https://www.ngdc.noaa.gov/mgg/pad/packager_manual.pdf)

**OR**

-   You can use the following automation scripts to fill in the Passive Packer database, which will pre-populate the majority of the fields based on the Package ID (Drift ID)

::: callout-note
## Note: The majority of the information required by Passive Packer can be found in the [Deployment Details spreadsheet](https://docs.google.com/spreadsheets/d/10bxlwfVOe1LFfj69B_YddxcA0V14m7codYwgD2YncFk/edit#gid=42687545%5D)
:::

## Automation Code (*WORK IN PROGRESS)*

The following code transfers our deployment details metadata into a Passive Packer ready database, containing JSON strings for all Passive Packer fields. This automation script is for ADRIFT deployments, however similar scripts can be found in our [Passive Packer Repository](https://github.com/Kourtney-Burger/ADRIFT-Deployment-PassivePacker) for CCES and PASCAL.

A folder manipulation automation code was also created to transfer all raw and ancillary data to Passive Packer specific directories to expedite the packaging process.

[Here is our mapping spreadsheet](https://docs.google.com/spreadsheets/d/1G_QF8C8QnqvQg8lf0nBXWtaGW7ApnxId0c-qkmUYwcg/edit#gid=0) where we linked [our deployment metadata fields](https://docs.google.com/spreadsheets/d/10bxlwfVOe1LFfj69B_YddxcA0V14m7codYwgD2YncFk/edit#gid=42687545) to their [respective Passive Packer fields](https://www.ngdc.noaa.gov/mgg/pad/packager_manual.pdf).

### Deployment Script

[The deployment automation code can be found here](https://github.com/Kourtney-Burger/ADRIFT-Deployment-PassivePacker/blob/4c227f577b94a7e9807ee30a2f191a447ae22b56/ADRIFT_Working_Scripts/ADRIFT_PassivePacker_Deployment.Rmd)

### Folder Manipulation

[The data folder manipulation code can be found here](https://github.com/Kourtney-Burger/ADRIFT-Deployment-PassivePacker/blob/4c227f577b94a7e9807ee30a2f191a447ae22b56/ADRIFT_Working_Scripts/ADRIFTDataFolderManipulation.Rmd)

## Complete Package Process

Once both scripts have been run and the Passive Packer database is updated, you can open Passive Packer and select a drift from the dataset drop down. All required fields should auto-populate. Once the data has been quality checked, select 'Package Data' and Passive Packer will automatically prepare the data package for NCEI.

The packaged data is now ready to be shipped to NCEI following the hard drive guidelines above.

::: callout-note
## Note: Passive Packer will crash if one of the JSON strings are not formatted properly
:::
