---
title: Data Quality Check
---

## Deployment Details Quality Check

-   Scan for any errors or mistakes in the [Deployment Details](https://docs.google.com/spreadsheets/d/10bxlwfVOe1LFfj69B_YddxcA0V14m7codYwgD2YncFk/edit?usp=sharing) spreadsheet (hydrophone, array, recorder, GPS, dates, etc.)
-   Reach out to deployment/retrieval team for corrections if needed

## Check Recording Time: UTC vs Local Time

-   Check log files from extraced SUD files for Soundtrap Recording time (UTC vs Local Time), fix if needed
-   Check Taiki's script
-   Rename if on local time

## Assess Data Quality

-   Scan the LTSA and define overall deployment as good, compromised, or unusable
-   Record Data Quality in [Deployment Details](https://docs.google.com/spreadsheets/d/10bxlwfVOe1LFfj69B_YddxcA0V14m7codYwgD2YncFk/edit?usp=sharing) spreadsheet

## Run Data Check on GPS Data

-   Review [drift tracks created by Driftwatch](https://drive.google.com/file/d/1Ca2MKzXSDYh-o71WvVr2EoC9zs7w3gbo/view?usp=share_link)
-   Look at the image that is associated with the drift number and ensure all points are from the drift (no points from when the array was on the boat or land)

## Run Recording QAQC 

-   soundtrapQAQC function in PAMmisc
-   Matlab QAQC script

## Scan LTSA for Noisy Data

If drift has been determined to be compromised in the data quality check above, scan the LTSA to log time periods with noisy/compromised data

-   Use the LTSA created with 500 Hz wav files, with 1s and 5Hz parameters
-   View LTSA at 2 hour windows and scan through
-   Use Logger to define start/end times of the noisy/bad data and include the type of noise in the comments (e.g. strumming, impulses, etc.)
-   Split between Anne and Cory
